import { StyleSheet } from "react-native";
import { moderateScale } from "../../utils/scalingUtils";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: "#fff" },
  appBar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#2E7D32",
    paddingVertical: moderateScale(20),
    paddingHorizontal: moderateScale(16),
    elevation: 4,
  },
  backButton: { paddingRight: moderateScale(10) },
  title: { color: "#fff", fontSize: moderateScale(18), fontWeight: "bold" },
  content: { padding: moderateScale(16) },
  label: { fontSize: moderateScale(16), fontWeight: "600", marginBottom: moderateScale(8), color: "#000" },
  dropdown: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: moderateScale(8),
    paddingVertical: moderateScale(12),
    paddingHorizontal: moderateScale(16),
    justifyContent: "center",
  },
  dropdownText: { fontSize: moderateScale(15), color: "#000" },
  modalOverlay: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(0,0,0,0.4)" },
  modalContainer: {
    backgroundColor: "#fff",
    borderTopLeftRadius: moderateScale(20),
    borderTopRightRadius: moderateScale(20),
    maxHeight: "70%",
    paddingHorizontal: moderateScale(16),
    paddingTop: moderateScale(12),
    paddingBottom: moderateScale(24),
  },
  modalHeader: { alignItems: "center", marginBottom: moderateScale(10) },
  modalTitle: { fontSize: moderateScale(18), fontWeight: "bold", color: "#2E7D32" },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f2f2f2",
    borderRadius: moderateScale(8),
    paddingHorizontal: moderateScale(10),
    marginBottom: moderateScale(10),
  },
  searchInput: { flex: 1, paddingVertical: moderateScale(8), paddingHorizontal: moderateScale(8), color: "#000" },
  productRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: moderateScale(12),
    borderBottomWidth: 1,
    borderColor: "#eee",
  },
  radioCircle: {
    height: moderateScale(18),
    width: moderateScale(18),
    borderRadius: moderateScale(9),
    borderWidth: 2,
    borderColor: "#2E7D32",
    marginRight: moderateScale(12),
  },
  radioSelected: { backgroundColor: "#2E7D32" },
  productText: { fontSize: moderateScale(16), color: "#000" },
  input: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: moderateScale(8),
    paddingVertical: moderateScale(10),
    paddingHorizontal: moderateScale(16),
    fontSize: moderateScale(15),
    color: "#000",
  },
  totalBox: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: moderateScale(8),
    paddingVertical: moderateScale(12),
    paddingHorizontal: moderateScale(16),
    backgroundColor: "#f9f9f9",
  },
  totalText: { fontSize: moderateScale(16), fontWeight: "bold", color: "#000" },
  dateBox: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: moderateScale(8),
    paddingVertical: moderateScale(12),
    paddingHorizontal: moderateScale(16),
  },
  dateText: { marginLeft: moderateScale(8), fontSize: moderateScale(15), color: "#000" },
  buttonRow: { flexDirection: "row", justifyContent: "space-between", marginTop: moderateScale(30) },
  button: { flex: 0.48, borderRadius: moderateScale(8), paddingVertical: moderateScale(12), alignItems: "center" },
  buttonText: { color: "#fff", fontSize: moderateScale(16), fontWeight: "bold" },
});
